version: '3'

services:

  backend-lyncas:
    container_name: backend-lyncas
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres-lyncas
    networks:
      - micro-service-connect
    ports:
      - '3333:3333'

  postgres-lyncas:
    container_name: postgres-lyncas
    image: postgres:12
    restart: unless-stopped
    environment: 
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - micro-service-connect

volumes:
  postgres-lyncas-data:

networks:
  micro-service-connect:
    driver: bridge